insert into goods_goodstype(id,name,cover,intro,parent_id) values(10001,'女装 / 男装 / 内衣','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10002,'鞋子 / 箱包 / 配件','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10003,'童装玩具 / 孕产 / 用品','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10004,'美妆 / 洗护 / 保健品','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10005,'珠宝 / 眼镜 / 手表','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10006,'运动 / 户外 / 乐器','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10007,'游戏 / 动漫 / 影视','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10008,'美食 / 生鲜 / 零食','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10009,'鲜花 / 宠物 / 农资','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10010,'工具 / 装修 / 建材','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10011,'家具 / 家饰 / 家纺','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10012,'汽车 / 二手车 / 用品','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10013,'办公 / DIY / 五金电子','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10014,'百货 / 餐厨 / 家庭保健','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10015,'女装 / 男装 / 内衣','static/image/goods/shangpin3.jpg','',null)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(10016,'学习 / 卡券 / 本地服务','static/image/goods/shangpin3.jpg','',null)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(100001,'夏上新','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100002,'连衣裙','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100003,'衬衫','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100004,'裤子','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100005,'牛仔裤','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100006,'西装','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100007,'短外套','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100008,'时尚套装','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100009,'风衣','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100010,'休闲裤','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100011,'皮衣','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100012,'毛呢外套','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100013,'马夹','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100014,'阔腿裤','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100015,'背心吊带','static/image/goods/shangpin.jpg','',10001)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(100016,'皮草','static/image/goods/shangpin.jpg','',10001)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(200001,'流行女鞋','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200002,'靴子','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200003,'运动风','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200004,'水晶鞋','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200005,'板鞋','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200006,'休闲鞋','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200007,'女包','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200008,'旅行箱','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200009,'迷你包','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200010,'贝壳包','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200011,'宽肩带','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200012,'披肩','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200013,'方巾','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200014,'八角帽','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200015,'鸭舌帽','static/image/goods/shangpin.jpg','',10002)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(200016,'贝雷帽','static/image/goods/shangpin.jpg','',10002)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(300001,'保暖连体','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300002,'羽绒','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300003,'童鞋','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300004,'新生儿','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300005,'三洋','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300006,'长靴','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300007,'湿巾','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300008,'纸尿裤','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300009,'美赞臣','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300010,'维生素','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300011,'宝宝调料','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300012,'奶瓶','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300013,'餐具','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300014,'描红本','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300015,'美素佳儿','static/image/goods/shangpin.jpg','',10003)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(300016,'可瑞康','static/image/goods/shangpin.jpg','',10003)

insert into goods_goodstype(id,name,cover,intro,parent_id) values(400001,'厨房电器','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400002,'烤箱','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400003,'电暖桌','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400004,'个人护理','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400005,'卷发器','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400006,'剃须刀','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400007,'电饭煲','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400008,'吹风机','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400009,'扫地机器人','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400010,'豆浆机','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400011,'烤箱','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400012,'数码相机','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400013,'鼠标键盘','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400014,'无人机','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400015,'蓝牙音箱','static/image/goods/shangpin.jpg','',10004)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(400016,'吸尘器','static/image/goods/shangpin.jpg','',10004)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(500001,'面膜','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500002,'爽肤水','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500003,'洁面','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500004,'防晒 ','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500005,'面霜','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500006,'精华','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500007,'隔离','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500008,' 眼霜','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500009,'胶原蛋白','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500010,'褪黑素','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500011,'香水','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500012,'蔓越莓','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500013,'彩妆盘','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500014,'腮红','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500015,'粉底液','static/image/goods/shangpin.jpg','',10005)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(500016,'唇膏','static/image/goods/shangpin.jpg','',10005)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(600001,'琥珀蜜蜡','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600002,'翡翠手镯','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600003,'彩色宝石','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600004,'钻戒','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600005,'铂金','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600006,'防辐射眼镜','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600007,'琥珀原石','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600008,'雷朋','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600009,'复古眼镜','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600010,'超耐磨','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600011,'怀表','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600012,'学生表','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600013,'电子表','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600014,'色盲眼镜','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600015,'光能表','static/image/goods/shangpin.jpg','',10006)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(600016,'眼镜片','static/image/goods/shangpin.jpg','',10006)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(700001,'耐克','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700002,'New Balance','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700003,'匡威','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700004,'亚瑟士','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700005,'Under Armour','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700006,'羽毛球','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700007,'彪马','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700008,'李宁','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700009,'阿迪达斯','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700010,'Hyperdunk','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700011,'架子鼓','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700012,'尤克里里','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700013,'葫芦丝','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700014,'贝斯','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700015,'大提琴','static/image/goods/shangpin.jpg','',10007)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(700016,'萨克斯','static/image/goods/shangpin.jpg','',10007)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(800001,'薯片','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800002,'芒果干','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800003,'绿豆糕','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800004,'核桃','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800005,'猪肉脯','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800006,'牛奶','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800007,'柚子茶','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800008,'冰皮月饼','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800009,'红酒','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800010,'蛋黄酥','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800011,'腰果','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800012,'山楂','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800013,'罗汉果','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800014,'开心果','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800015,'棒棒糖','static/image/goods/shangpin.jpg','',10008)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(800016,'糖果','static/image/goods/shangpin.jpg','',10008)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(900001,'鲜花速递','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900002,'永生花','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900003,'多肉植物','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900004,'干花','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900005,'食虫植物','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900006,'桌面盆栽','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900007,'蔬菜种子','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900008,'苔藓景观','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900009,'空气凤梨','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900010,'洒水壶','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900011,'花卉药剂','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900012,'花盆花器','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900013,'仿真植物','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900014,'绣球','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900015,'铁线莲','static/image/goods/shangpin.jpg','',10009)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(900016,'花卉药剂','static/image/goods/shangpin.jpg','',10009)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000001,'电钻 ','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000002,'电动螺丝批','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000003,'云石片','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000004,'电烙铁','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000005,'测电笔','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000006,'磨砂机','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000007,'修边机','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000008,'打磨机','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000009,'电工套管','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000010,'断路器','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000011,'插座','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000012,'电锯','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000013,'焊接设备','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000014,'楼宇智能系统','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000015,'断路器','static/image/goods/shangpin.jpg','',10010)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1000016,'角磨机','static/image/goods/shangpin.jpg','',10010)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100001,'衣柜','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100002,'书桌 ','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100003,'现代简约','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100004,'北欧家具','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100005,'中式家具','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100006,'佛山家具','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100007,'茶几','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100008,'沙发','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100009,'高低床','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100010,'餐桌','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100011,'床垫','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100012,'鞋柜','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100013,'椅凳','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100014,'电脑桌','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100015,'坐具','static/image/goods/shangpin.jpg','',10011)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1100016,'美式家具','static/image/goods/shangpin.jpg','',10011)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200001,'首付一成开新车','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200002,'超级试驾','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200003,'新能源车','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200004,'轿车','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200005,'SUV','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200006,'小型车','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200007,'雪佛兰','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200008,'日产','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200009,'本田','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200010,'起亚','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200011,'玛莎拉蒂','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200012,'沃尔沃','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200013,'荣威','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200014,'别克','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200015,'smart','static/image/goods/shangpin.jpg','',10012)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1200016,'Mini','static/image/goods/shangpin.jpg','',10012)




insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300001,'文化衫','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300002,'工作服','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300003,'卫衣定制','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300004,'LOGO设计','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300005,'VI设计','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300006,'编织袋','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300007,'飞机盒','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300008,'泡沫箱','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300009,'气柱袋','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300010,'纸手提袋','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300011,'广告扇','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300012,'水晶奖杯','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300013,'胸牌工牌','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300014,'奖杯','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300015,'徽章','static/image/goods/shangpin.jpg','',10013)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1300016,'洗照片','static/image/goods/shangpin.jpg','',10013)



insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400001,'饭盒','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400002,'口罩','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400003,'省力拖把','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400004,'家务清洁','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400005,'玻璃杯','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400006,'马克杯','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400007,'餐具套装','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400008,'碗 盘 碟 ','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400009,'垃圾桶','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400010,'居家鞋','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400011,'围裙','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400012,'拖把','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400013,'浴帘','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400014,'浴室置物架','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400015,'潮州陶瓷','static/image/goods/shangpin.jpg','',10014)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1400016,'景德镇陶瓷','static/image/goods/shangpin.jpg','',10014)




insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500001,'劳动节福利','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500002,'超市卡','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500003,'沃尔玛','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500004,'家乐福','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500005,'银泰卡','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500006,'面包券','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500007,'来伊份券','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500008,'粽子券','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500009,'云服务器','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500010,'财务管理','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500011,'网页设计','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500012,'软件','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500013,'咖啡','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500014,'哈根达斯','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500015,'冰淇淋','static/image/goods/shangpin.jpg','',10015)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1500016,'网站建设','static/image/goods/shangpin.jpg','',10015)


insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600001,'婚纱摄影','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600002,'青岛婚拍','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600003,'丽江婚拍','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600004,'三亚婚拍','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600005,'厦门婚拍','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600006,'新娘跟妆','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600007,'婚礼司仪','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600008,'入职体检','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600009,'法律咨询','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600010,'上门按摩','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600011,'专业翻译','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600012,'礼服租赁','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600013,'家电清洗','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600014,'家庭保洁','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600015,'名企招聘','static/image/goods/shangpin.jpg','',10016)
insert into goods_goodstype(id,name,cover,intro,parent_id) values(1600016,'上门美甲','static/image/goods/shangpin.jpg','',10016)
